name: inputdemo

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "this is input demo"
        required: true
        default: dev
      tag:
        description: "this is tag"
        required: true
        default: "1.0.0"

jobs:
  inputdemo:
    runs-on: ubuntu-latest
    steps:
      - name: run input demo
        run: echo "Deploy the ${{ inputs.tag }} application in ${{ inputs.environment }}"
